# baseURL = "http://example.org/"
# languageCode = "en-gb"
# title = "De Satirica"
# # theme = "pickles"
# # theme = "sam"
# theme = "coder"
# # theme = "minimal"
# # theme = "academic"

baseurl = "https://zaeph.net/"
title = "De Satirica"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Leo Vivier"
    info = "English Professor & Professional Trifler"
    description = "Leo Vivier's personal website"
    keywords = "blog,developer,personal"
    avatar = false
    avatarurl = "img/logo.svg"
    # avatarurl = "img/murrow.jpg"

    colorscheme = "light"

    noreadingtime = true

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    # footercontent = "Dream on."

    hidecredits = false
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/zaeph/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/leo-vivier/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/zaeph/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Categories"
    weight = 1
    url  = "/categories/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

# Taxonomies
[taxonomies]
    category = "categories"
    tag = "tags"

[markup.goldmark.renderer]
        unsafe = true